[package]
name = "stader-utils"
version = "0.1.0"
authors = ["Bharath Vedartham <vedabharath12345@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "0.16.0", features = ["staking"] }
cosmwasm-storage = { version = "0.16.0", features = ["iterator"] }
cw-storage-plus = { version = "0.8.0", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.24" }
cosmwasm-bignumber = "2.1.1"
terra-cosmwasm = { version = "2.1.0" }
cw20 = "0.8.0"

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }